work_dir: ./work_dir/ntu60/xsub/ctrgcn_jointmotion

# feeder
feeder: feeders.feeder_ntu.Feeder
# feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: /home/featurize/data/NTU60_CS.npz
  # data_path: /home/featurize/work/BlockGCN/data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: /home/featurize/data/NTU60_CS.npz
  # data_path: /home/featurize/work/BlockGCN/data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  window_size: 64
  graph_args:
    labeling_mode: 'spatial'
  # joint_label: [ 0, 4, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 2, 3, 3, 3, 1, 0, 1, 0, 1 ]


#optim
weight_decay: 0.0004
base_lr: 0.05
lr_decay_rate: 0.1
step: [110, 120]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True
